import{S as M,a as $,i as n}from"./assets/vendor-BMHzDZyJ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const B=new M(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more");function y(o){const r=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:t,views:s,comments:u,downloads:q})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${i}" alt="${e}" />
          </a>
          <ul class="image-stats">
            <li><b>Likes:</b> ${t}</li>
            <li><b>Views:</b> ${s}</li>
            <li><b>Comments:</b> ${u}</li>
            <li><b>Downloads:</b> ${q}</li>
          </ul>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",r),B.refresh()}function E(){g.innerHTML=""}function p(){f.classList.remove("is-hidden")}function b(){f.classList.add("is-hidden")}function R(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}async function w(o,r){const e="https://pixabay.com"+"/api/",s={key:"50306313-7dd778a7e5a97bb6309a7d780",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await $.get(e,{params:s})).data}const v=document.querySelector(".form"),m=v.elements["search-text"],O=document.querySelector(".load-more");let c,l=0;const d=15;let S=0;v.addEventListener("submit",async o=>{if(o.preventDefault(),c=m.value.trim(),l=1,!c){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}E(),L(),p();try{const r=await w(c,l,d),i=r.hits;if(S=r.totalHits,i.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(i),P()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b(),m.value=""}});O.addEventListener("click",async()=>{l+=1,p();try{const o=await w(c,l,d);y(o.hits);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),P()}catch{n.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{b()}});function P(){l*d>=S?(L(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):R()}
//# sourceMappingURL=index.js.map
